### ISSUE TITLE
add_collaborator method not working

### ISSUE THREAD

**Issue by ptoge** [octokit/octokit.rb#1033] opened 2018-07-18 21:44 UTC
Hi,

I am trying to call the 'add_collaborator' method in my code like the following:

> @octokit_client = Octokit::Client.new(:access_token => 'myoauthtoken', :api_endpoint => 'mygheinstance.com/api/v3/')
>
> @octokit_client.add_collaborator('myorganization/myrepo', 'myotherusername', permission: 'admin')

But this does not work and I get errors like this in pry:

> => false

What is interesting is, the 'update_organization_membership' method:

> @octokit_client.update_organization_membership('myorganization', {:user => 'myotherusername', :role => 'admin'})

Works, as it returns an object that contains repo information.

Why is 'add_collaborator' not working?

Thanks in advance!

**Comment by tarebyte** [comment] 2018-07-18 21:48
@ptoge are you able to reproduce this issue using CURL, and if so would you mind dropping the requests in this issue?

Thanks!

**Comment by ptoge** [comment] 2018-07-19 21:39
Hi tarebyte,

No, we are unable to reproduce this issue with cURL.  The following command works just fine for adding a collaborator to a repo:

> curl -X PUT -u <oauth_token>:x-oauth-basic 'https://<github_url>/api/v3/repos/<org>/<repo>/collaborators/<username_to_add_as_collaborator>'

Thank you!

**Comment by kytrinyx** [comment] 2018-07-26 16:55
Thank you @ptoge, it looks like this is a bug in the `add_collaborator` method specifically.

**Comment by ptoge** [comment] 2018-07-26 20:18
Hi all,

Sorry I discovered this was a false alarm.  This was not a bug but an issue on my end.  I incorrectly set the scopes for the impersonation token I generated previously.  After adjusting the scopes I was able to use the 'add_collaborator' method.

**Comment by kytrinyx** [comment] 2018-07-26 21:13
@ptoge thank you so much for checking back in and letting us know. I'm going to close this issue.

**Closed by kytrinyx** 2018-07-26 21:13 UTC
Labels: bug
