### ISSUE TITLE
Configuration option for timeout

### ISSUE THREAD

**Issue by mayrsascha** [octokit/octokit.rb#979] opened 2018-01-19 16:26 UTC
On the app I am working on we are making calls to the GitHub API, some of them are needed to render certain views. Recently some of those calls were slow and the view was "loading" for about 60 seconds before showing an ugly load balancer timeout page to the user (60 seconds are set on the load balancer as timeout).

I would like to configure a shorter timeout/ fewer retries to the API and show an error page to the user sooner, couldn't find any documentation on that, is that possible?

**Comment by tarebyte** [comment] 2018-01-19 16:53
@mayrsascha we have an example of that for the stats api

https://github.com/octokit/octokit.rb/blob/495565432a0cafb21a06389581ee36169ab5cb34/lib/octokit/client/stats.rb#L84-L102

And it's been requested https://github.com/octokit/octokit.rb/issues/888 but we haven't had time to implement it.

Hope that helps!

**Comment by mayrsascha** [comment] 2018-01-19 17:54
@tarebyte Thanks for your quick reply. Indeed my request is the same as in #888 so feel free to close this issue. Is there an ETA on this feature?

**Comment by tarebyte** [comment] 2018-01-19 18:00
@mayrsascha not at the moment I'm afraid, I've been super busy with work

But I'd be happy to review a PR if one should come in  😄

**Comment by tarebyte** [comment] 2018-01-19 18:00
Closing because this is a duplicate of #888

**Closed by tarebyte** 2018-01-19 18:00 UTC
Labels: question
