### ISSUE TITLE
Upgrade from 4.20.0 to 4.21.0 causes Octokit::UnsupportedMediaType

### ISSUE THREAD

**Issue by poloka** [octokit/octokit.rb#1337] opened 2021-05-04 21:12 UTC
I am logging an issue with my initial findings but upon attempting to create a check-run when upgrading from 4.20.0 to 4.21.0 I am receiving the following error:
```
exception: { [-]
     message: POST https://<github_url>/api/v3/repos/orion-delivery/application-config/check-runs: 415 - If you would like to help us test the Checks API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details. // See: https://docs.github.com/enterprise/2.22/rest/reference/checks#create-a-check-run
     stack_trace: Octokit::UnsupportedMediaType(POST https://<github_url>/api/v3/repos/orion-delivery/application-config/check-runs: 415 - If you would like to help us test the Checks API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details. // See: https://docs.github.com/enterprise/2.22/rest/reference/checks#create-a-check-run)
 /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/middleware.rb:19:in `block in call'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/response.rb:59:in `on_complete'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/middleware.rb:18:in `call'
 /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
 /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/request/retry.rb:148:in `call'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/rack_builder.rb:154:in `build_response'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/connection.rb:492:in `run_request'
 /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/connection.rb:279:in `post'
 /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
 /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/connection.rb:156:in `request'
 /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/connection.rb:28:in `post'
 /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/client/checks.rb:29:in `create_check_run'
```

I will be reviewing further but in case someone has already run across this please let me know your findings and/or possible solutions to the issue.

**Comment by tarebyte** [comment] 2021-05-04 21:23
Seems to be a duplicate of https://github.com/octokit/octokit.rb/issues/1334

@poloka what version of Enterprise are you running? It could be that your version still requires the preview header.

**Comment by poloka** [comment] 2021-05-04 22:37
@tarebyte you would be correct.  my company is on GitHub Enterprise Server 2.22.4 and they don't plan to upgrade to a 3.x version until EOY.

**Comment by tarebyte** [comment] 2021-05-06 20:14
@poloka the workaround would be something like what I've suggested in https://github.com/octokit/octokit.rb/issues/1334#issuecomment-827764387.

**Closed by tarebyte** 2021-05-06 20:14 UTC
