### ISSUE TITLE
CheckSuite and CheckRun APIs

### ISSUE THREAD

**Issue by jondavidjohn** [octokit/octokit.rb#1075] opened 2018-09-27 01:51 UTC
Looks like we don't have methods for the new Checks API

 - [ ] [CheckSuites](https://developer.github.com/v3/checks/suites/)
 - [ ] [CheckRuns](https://developer.github.com/v3/checks/runs/)

Thanks!

**Comment by tarebyte** [comment] 2018-09-28 13:11
Duplicate of https://github.com/octokit/octokit.rb/issues/1074

I don't have time to implement it right now, but you're welcome to take it on @jondavidjohn if you fancy contributing 😄

**Closed by tarebyte** 2018-09-28 13:11 UTC

**Comment by laserlemon** [comment] 2019-01-16 22:13
I have a solid start on adding this functionality at https://github.com/laserlemon/octokit.rb. Here's the [diff](https://github.com/octokit/octokit.rb/compare/master...laserlemon:checks) thus far. Please feel free to contribute to my branch and I'll open a PR when it's ready. I'm open to implementation feedback from the Octokit folks as well!
