### ISSUE TITLE
contributors_stats should not be retried on 2xx codes

### ISSUE THREAD

**Issue by skamsie** [octokit/octokit.rb#940] opened 2017-09-23 20:18 UTC
If github returns a `2xx` response code, but not `200`, the request should not be retried even if params like `:retry_wait` or `:retry_timeout` are passed. 

One example would be when trying to get contributor stats for an empty repository, github returns 204 (empty content). But the `get_stats` method will retry the request even if it is technically success and nothing can change.

Example of empty repo:

```@client.contributors_stats("ansible/ansible.github.io", retry_timeout: 10, retry_wait: 1)```

https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/stats.rb#L97

Suggested fix:

`return data if last_response.status.to_s[0] == "2"`

EDIT: I saw later that is the same with: https://github.com/octokit/octokit.rb/issues/912

**Comment by tarebyte** [comment] 2017-11-16 15:13
Going to close this as it is a duplicate of https://github.com/octokit/octokit.rb/issues/912 like you mentioned.

@skamsie would you be interested in open in a PR to make this change? It seems like the correct approach.

Thanks!

**Closed by tarebyte** 2017-11-16 15:13 UTC
